spring.application.name=CachingApplication

spring.datasource.url=jdbc:postgresql://localhost:5432/SB-Caching-DB
spring.datasource.username=postgres
spring.datasource.password=Swift@5140

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true