spring.application.name=CachingApplication

spring.datasource.url=jdbc:postgresql://localhost:5432/SB-Caching-DB
spring.datasource.username=postgres
spring.datasource.password=Swift@5140

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# redis-configurations
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
#spring.data.redis.password=your-redis-password
#spring.data.redis.ssl.enabled=false